### get users

GET http://localhost:3000/users

### resister user

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "ja",
  "first_name": "jarjar2",
  "last_name": "jarjar2",
  "email": "jarjar2@esxample.com",
  "password": "jarjar"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "jarjr",
  "password": "jarjar"
}